cache:
  paths:
    - /root/.m2/repository/

variables:
  JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"

default-job:
  script:
      - id
      - locale -a
      - locale
      - ./.ci.sh
  artifacts:
     paths:
       - ./CHANGELOG.html
       - ./*.jar
     expire_in: 5 mins
  except:
      - tags

release-job:
  script:
      - ./.ci.sh
  artifacts:
     paths:
       - ./CHANGELOG.html
       - ./*.jar
  only:
     - tags
