image: registry.gitlab.com/orange-opensource/documentare-simdoc-ci-docker:master

cache:
  paths:
    - ~/.m2

variables:
  JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"

stages:
  - build
  - deploy

default-job:
  stage: build
  script:
      - ./.ci.sh
  artifacts:
     paths:
       - ./CHANGELOG.html
       - ./*.jar
     expire_in: 5 mins
  except:
      - tags

release-job:
  stage: build
  script:
      - ./.ci.sh
  artifacts:
     paths:
       - ./CHANGELOG.html
       - ./*.jar
  only:
     - tags

deploy-job:
  image: docker:latest
  services:
     - docker:dind
  stage: deploy
  before_script:
#    - env | grep ^DOCKER_
#    - env | grep ^CI_
#    - docker info
    - ls
    - copy simdoc-server*.jar simdoc/simdoc-server
    - ls simdoc/simdoc-server
    - docker login $CI_REGISTRY --username gitlab-ci-token --password $CI_BUILD_TOKEN

  script:
      - (cd simdoc/simdoc-server && docker build --pull -t $CI_REGISTRY_IMAGE:clustering-$CI_BUILD_TAG .)
      - docker push $CI_REGISTRY_IMAGE:clustering-$CI_BUILD_TAG
#  only:
#     - tags
