image: registry.gitlab.com/orange-opensource/documentare-simdoc-ci-docker:master

# Cache downloaded dependencies and plugins between builds.
cache:
  paths:
    - /root/.m2/repository/

variables:
  - JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"

default-job:
  script:
      - locale -a
      - locale
      - ./.ci.sh
  artifacts:
     paths:
       - ./CHANGELOG.html
       - ./*.jar
     expire_in: 5 mins
  except:
      - tags

release-job:
  script:
      - ./.ci.sh
  artifacts:
     paths:
       - ./CHANGELOG.html
       - ./*.jar
  only:
     - tags

