language: java

# enable container based build
dist: trusty
sudo: false

# we need java 8
jdk:
- oraclejdk8

# system dependencies
# NB: we rely on Nu package for opencv libraries
addons:
  apt:
    packages:

# skip build without tests
install: true
script:
  - tar xvjf 3rdparty/graphviz_bin.tar.bz2
  - mkdir -p /opt/local
  - ln -s bin /opt/local/bin
  - ./.ci.sh

# avoid downloading each time maven dependencies
cache:
  directories:
    $HOME/.m2

# say 'go to hell' when there is a pb
#notifications:
#email:
#  on_success: change
#  on_failure: always
#  recipients:
#    - christophe.maldivi@orange.com
#    - joel.gardes@orange.com
