language: java

# enable container based build
#dist: precise
#sudo: false

# we need java 8
jdk:
- oraclejdk8

# system dependencies
addons:
  apt:
    packages:
#      - libopencv-core2.4

# skip build without tests
install: true
script:
  - apt-cache search opencv
  - ./.ci.sh

# avoid downloading each time maven dependencies
cache:
  directories:
    $HOME/.m2

# say 'go to hell' when there is a pb
#notifications:
#email:
#  on_success: change
#  on_failure: always
#  recipients:
#    - christophe.maldivi@orange.com
#    - joel.gardes@orange.com
