language: java

dist: trusty
sudo: required

jdk:
- oraclejdk8

addons:
  apt:
    packages:
    - maven
    - libgts-0.7-5
    - devscripts
    - fakeroot
    - debhelper
    - libopencv-core2.4
    - libopencv2.4-java


install: true

before_script:
- wget https://gitlab.com/Orange-OpenSource/documentare/documentare-graphviz/-/jobs/21454333/artifacts/raw/graphviz_2.38.0-18_amd64.deb
- sudo dpkg --force-all -i graphviz_2.38.0-18_amd64.deb

script:
- ./.ci.sh

before_deploy:
- export TARBALL=$(ls *.tar)
- echo Will deploy ${TARBALL}

deploy:
  provider: releases
  api_key:
    secure: epwSFkdzSebdBwR3i4MiK2wfV3Xb7SZSFOSVMPBLds9yfLIOIonBTYIP4gm1igEJ37afIHUOxL63xC+09p53STiPj0rFoephPqB6f1ZSjaN8iiRQVY8mBpHhVNJDth7ngNaOrt5QIWqd6EgabkPOWo5a7Y1wf8LUPgj94QwEO2ufjlM6tseh9eaLyjN9JvNPCFch+vnZVBllyDAicEw085udNWDkACtCUcnpZMvA3zSyT25QOOYV6YYZMepzZuqFEJ4rE15/8Eyec6UysmKMALtyBwJ2nknHpHSWVPY9qQrUqVxIIhcmfuIGrJzGyV8cJZ6gkcwtJnmMKAxks2duO0sR6YCXiijO8+791QkuNZPZ0M15uOud0ZyEVXAg22ot+ls3vJ5rrn3ufrCzrnco3G7M2l5egrXnY21Xfg2z6qTXVlxf0d8FQ/TCjW9eTpDi2mt0f99+CbV01LvRnRXlxB95pxwMdEz/6mpqQ9b1/g45/v7D5gEh/LSEqPL5qGYcYsUNes0k7iVEjDYxyQs+MXEIyPpf4UxP9j7FeHRnG1cQmZz71SqkmPIEsi8lvsREmjKfI0/xWBCMU/23tY6hp4NaKtKE8u2qNoTE0x1K0PAB61grBZkDL4qKQBKfOowmHr7SfBD4tSZI7f5zecXUIG2zWgLnkJ2cj9if8ZGHhe8=
  file: "${TARBALL}"
  skip_cleanup: true
  on:
    tags: true
    repo: Orange-OpenSource/documentare-simdoc

cache:
  directories: $HOME/.m2

# say 'go to hell' when there is a pb
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - christophe.maldivi@orange.com
    - joel.gardes@orange.com
    - denis.boisset@orange.com

