language: java

# enable container based build
dist: trusty
sudo: false

# we need java 8
jdk:
- oraclejdk8

# system dependencies
# NB: we rely on Nu package for opencv libraries
addons:
  apt:
    packages:
      - libgts-0.7-5

# skip build without tests
install: true

before_script:
 - tar xvjf 3rdparty/graphviz_bin.tar.bz2 && mkdir -p /opt/local && mv bin /opt/local/
 - /opt/local/bin/sfdp -V
 - /opt/local/bin/gvmap --help

script:
  - ./.ci.sh

# deploy to github releases
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: *.jar
  skip_cleanup: true
  on:
    tags: true

# avoid downloading each time maven dependencies
cache:
  directories:
    $HOME/.m2
    $HOME/.gradle

# say 'go to hell' when there is a pb
#notifications:
#email:
#  on_success: change
#  on_failure: always
#  recipients:
#    - christophe.maldivi@orange.com
#    - joel.gardes@orange.com
