language: java

dist: trusty
sudo: false

jdk:
- oraclejdk8

addons:
  apt:
    packages:
    - libgts-0.7-5
    - devscripts
    - fakeroot

install: true

before_script:
- tar xvjf 3rdparty/graphviz-2.38-ubuntu-trusty.tar.bz2 && mv opt/local /opt/
- /opt/local/bin/sfdp -V
- /opt/local/bin/gvmap --help

script:
- ./.ci.sh

before_deploy:
- export TARBALL=$(ls *.tar.bz2)
- echo Will deploy ${TARBALL}

deploy:
  provider: releases
  api_key:
    secure: epwSFkdzSebdBwR3i4MiK2wfV3Xb7SZSFOSVMPBLds9yfLIOIonBTYIP4gm1igEJ37afIHUOxL63xC+09p53STiPj0rFoephPqB6f1ZSjaN8iiRQVY8mBpHhVNJDth7ngNaOrt5QIWqd6EgabkPOWo5a7Y1wf8LUPgj94QwEO2ufjlM6tseh9eaLyjN9JvNPCFch+vnZVBllyDAicEw085udNWDkACtCUcnpZMvA3zSyT25QOOYV6YYZMepzZuqFEJ4rE15/8Eyec6UysmKMALtyBwJ2nknHpHSWVPY9qQrUqVxIIhcmfuIGrJzGyV8cJZ6gkcwtJnmMKAxks2duO0sR6YCXiijO8+791QkuNZPZ0M15uOud0ZyEVXAg22ot+ls3vJ5rrn3ufrCzrnco3G7M2l5egrXnY21Xfg2z6qTXVlxf0d8FQ/TCjW9eTpDi2mt0f99+CbV01LvRnRXlxB95pxwMdEz/6mpqQ9b1/g45/v7D5gEh/LSEqPL5qGYcYsUNes0k7iVEjDYxyQs+MXEIyPpf4UxP9j7FeHRnG1cQmZz71SqkmPIEsi8lvsREmjKfI0/xWBCMU/23tY6hp4NaKtKE8u2qNoTE0x1K0PAB61grBZkDL4qKQBKfOowmHr7SfBD4tSZI7f5zecXUIG2zWgLnkJ2cj9if8ZGHhe8=
  file: "${TARBALL}"
  skip_cleanup: true
  on:
    tags: true
    repo: Orange-OpenSource/documentare-simdoc

cache:
  directories: $HOME/.m2

# say 'go to hell' when there is a pb
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - christophe.maldivi@orange.com
    - joel.gardes@orange.com

